1

In [2]:
def max(x,y,z):
    if x>y and x>z:
        print(f'Maximum value is {x}')
    elif y>x and y>z:
        print(f'Maximum value is {y}')
    else:
        print(f'Maximum value is {z}')
x=int(input("Enter first number : "))
y=int(input("Enter second number : "))
z=int(input("Enter third number : "))
max(x,y,z)

Enter first number : 15
Enter second number : 17
Enter third number : 13
Maximum value is 17


2


In [3]:
def AoC(r):
    Area_of_Circle=3.14*r**2
    print(f'Area of a circle : {Area_of_Circle}')
r=float(input("Radius : "))
AoC(r)

Radius : 5
Area of a circle : 78.5


3



In [4]:
def PrimeNo(n):
    for i in range(2,n):
        if n%i==0:
            return False
    else:
        return True
n=int(input("Enter the number : "))
PrimeNo(n)

Enter the number : 13


True

4

In [5]:
def Palindrome(string):
    if string==string[::-1]:
        return True
    else:
        return False
string=input("Enter a string : ")
Palindrome(string)

Enter a string : malayalam


True

5

In [6]:
def S(list1):
    sum=0
    for i in list_1:
        sum+=i
    return sum
list_1=[5,10,15,20,25]
print(list_1)
S(list_1)

[5, 10, 15, 20, 25]


75

6

In [8]:
def avg(list_01):
    sum=0
    for i in list_01:
        sum+=i
    avg=sum/len(list_01)
    return avg
list_01=[2,4,6,8,10]
avg(list_01)

6.0

7

In [9]:
def kth_largest(list2,k):
    list2.sort(reverse=True)
    print(f'{k}th largest element : {list2[k-1]}' )
list2=[4,3,5,9,11,2]
k=3
print(list2)
kth_largest(list2,k)

[4, 3, 5, 9, 11, 2]
3th largest element : 5


8

In [10]:
def SoD(n):
    if n<10:
        return n
    else:
        return n%10 + SoD(n//10)
n=4320820
SoD(n)

19

9

In [11]:
def Expo(b,e):
    if e==0:
        return 1
    else:
        for i in range(e):
            return b*Expo(b,e-1)
b=int(input("Enter base value : "))
e=int(input("Enter exponent value : "))
Power=Expo(b,e)
print(f'Power of the number : {Power}')

Enter base value : 2
Enter exponent value : 4
Power of the number : 16


10

In [12]:
def gcd(a,b):
    while b!=0:
        a,b=b,a%b
    return a
a=int(input("Enter the first number : "))
b=int(input("Enter the second number : "))
print(f"Greatest common divisor of {a} and {b} : {gcd(a,b)}")

Enter the first number : 10
Enter the second number : 15
Greatest common divisor of 10 and 15 : 5


11

In [13]:
import numpy as np
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12

In [14]:
a2=np.arange(1,10)
a2=a2.reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13

In [15]:
a3=np.eye(3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14

In [16]:
a4=np.random.randint(10,101,10)
print(a4)
print(f"mean : {a4.mean()}")
print(f"standard deviation : {a4.std()}")

[21 75 52 34 77 71 90 30 99 79]
mean : 62.8
standard deviation : 25.494313091354318


15

In [17]:
a5=np.arange(10,21)
a5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
a5[:5]

array([10, 11, 12, 13, 14])

16

In [19]:
a6=np.arange(2,33,2)
a6=a6.reshape(4,4)
a6

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [20]:
a6[1]

array([10, 12, 14, 16])

17

In [21]:
a7=np.arange(1,6)
a7


array([1, 2, 3, 4, 5])

In [22]:
a8=np.arange(6,11)
a8

array([ 6,  7,  8,  9, 10])

In [23]:
a9=a7+a8
a9

array([ 7,  9, 11, 13, 15])

18

In [24]:
a10=np.random.rand(10)
a10

array([0.9434262 , 0.59646343, 0.17068345, 0.85389808, 0.04033661,
       0.47798915, 0.55417634, 0.2976077 , 0.5036187 , 0.48708816])

In [25]:
a10[a10<0.5]=0
a10


array([0.9434262 , 0.59646343, 0.        , 0.85389808, 0.        ,
       0.        , 0.55417634, 0.        , 0.5036187 , 0.        ])